export const data=[
  {
    "orderId": Math.floor(100000 + Math.random() * 900000),
    "ticker": "LDR",
    "securityId": 4074,
    "targetPrice": 29.14,
    "targetQuantity": 571,
    "targetAmount": 16639,
    "account": "PF98262",
    "manager": "Rhianna Parmenter",
    "trader": "Graig Lacky",
    "tradeDate": "2022-01-11",
    "settlementDate": "2022-01-13",
    "status": "OPEN",
    "executedQuantity": 0,
    "broker": "CITI",
    "securityType": "GB",
    "transactionType": "SELLL",
    "duration": "FOK",
    "instruction": "LIM",
    "limit": ""
  },
  {
    "orderId": Math.floor(100000 + Math.random() * 900000),
    "ticker": "ORBK",
    "securityId": 4202,
    "targetPrice": 75.78,
    "targetQuantity": 473,
    "targetAmount": 35844,
    "account": "PF72763",
    "manager": "Gert Wheatland",
    "trader": "Nappy Madgwick",
    "tradeDate": "2022-01-11",
    "settlementDate": "2022-01-13",
    "status": "READY",
    "executedQuantity": 100,
    "broker": "BARC",
    "securityType": "PFD",
    "transactionType": "SELLL",
    "duration": "FOK",
    "instruction": "MO",
    "limit": ""
  },
  {
    "orderId": Math.floor(100000 + Math.random() * 900000),
    "ticker": "AOBC",
    "securityId": 2304,
    "targetPrice": 42.73,
    "targetQuantity": 449,
    "targetAmount": 19186,
    "account": "PF43537",
    "manager": "Corty Jellard",
    "trader": "Bryan Lorey",
    "tradeDate": "2022-01-11",
    "settlementDate": "2022-01-13",
    "status": "OPEN",
    "executedQuantity": 0,
    "broker": "JPM",
    "securityType": "GB",
    "transactionType": "SELLL",
    "duration": "FOK",
    "instruction": "LIM",
    "limit": ""
  },
  {
    "orderId": Math.floor(100000 + Math.random() * 900000),
    "ticker": "LLNW",
    "securityId": 4947,
    "targetPrice": 10.64,
    "targetQuantity": 100,
    "targetAmount": 1064,
    "account": "PF98765",
    "manager": "Kathie Ledger",
    "trader": "Gabie Prator",
    "tradeDate": "2022-01-11",
    "settlementDate": "2022-01-13",
    "status": "READY",
    "executedQuantity": 100,
    "broker": "JPM",
    "securityType": "PFD",
    "transactionType": "BUYL",
    "duration": "FOK",
    "instruction": "MO",
    "limit": ""
  },
  {
    "orderId": Math.floor(100000 + Math.random() * 900000),
    "ticker": "RTEC",
    "securityId": 1381,
    "targetPrice": 97.28,
    "targetQuantity": 236,
    "targetAmount": 22958,
    "account": "PF19827",
    "manager": "Haroun Sommers",
    "trader": "Ermina Mattedi",
    "tradeDate": "2022-01-11",
    "settlementDate": "2022-01-13",
    "status": "READY",
    "executedQuantity": 100,
    "broker": "CS",
    "securityType": "CB",
    "transactionType": "BUYL",
    "duration": "GTC",
    "instruction": "LIM",
    "limit": ""
  },
  {
    "orderId": Math.floor(100000 + Math.random() * 900000),
    "ticker": "GSL^B",
    "securityId": 1612,
    "targetPrice": 50.3,
    "targetQuantity": 103,
    "targetAmount": 5181,
    "account": "PF19827",
    "manager": "Ashlie Vondrasek",
    "trader": "Seline Langton",
    "tradeDate": "2022-01-11",
    "settlementDate": "2022-01-13",
    "status": "ACCT",
    "executedQuantity": 100,
    "broker": "JPM",
    "securityType": "CB",
    "transactionType": "BUYL",
    "duration": "FOK",
    "instruction": "MO",
    "limit": ""
  },
  {
    "orderId": Math.floor(100000 + Math.random() * 900000),
    "ticker": "SCVL",
    "securityId": 4223,
    "targetPrice": 39.81,
    "targetQuantity": 743,
    "targetAmount": 29579,
    "account": "PF98262",
    "manager": "Christian Manger",
    "trader": "Atlanta Yurkin",
    "tradeDate": "2022-01-11",
    "settlementDate": "2022-01-13",
    "status": "WORK",
    "executedQuantity": 0,
    "broker": "JPM",
    "securityType": "GB",
    "transactionType": "SELLL",
    "duration": "D",
    "instruction": "MO",
    "limit": ""
  },
  {
    "orderId": Math.floor(100000 + Math.random() * 900000),
    "ticker": "SINO",
    "securityId": 2595,
    "targetPrice": 43.55,
    "targetQuantity": 343,
    "targetAmount": 14938,
    "account": "PF19827",
    "manager": "Saleem Jeannaud",
    "trader": "Robyn Blant",
    "tradeDate": "2022-01-11",
    "settlementDate": "2022-01-13",
    "status": "OPEN",
    "executedQuantity": 0,
    "broker": "BARC",
    "securityType": "CB",
    "transactionType": "SELLL",
    "duration": "FOK",
    "instruction": "MKT",
    "limit": ""
  },
  {
    "orderId": Math.floor(100000 + Math.random() * 900000),
    "ticker": "DNP",
    "securityId": 3970,
    "targetPrice": 24.25,
    "targetQuantity": 390,
    "targetAmount": 9458,
    "account": "PF98383",
    "manager": "Danielle McEvilly",
    "trader": "Freeland Bolzmann",
    "tradeDate": "2022-01-11",
    "settlementDate": "2022-01-13",
    "status": "ACCT",
    "executedQuantity": 100,
    "broker": "CITI",
    "securityType": "PFD",
    "transactionType": "SELLL",
    "duration": "GTC",
    "instruction": "MO",
    "limit": ""
  },
  {
    "orderId": Math.floor(100000 + Math.random() * 900000),
    "ticker": "GTY",
    "securityId": 4659,
    "targetPrice": 76.23,
    "targetQuantity": 578,
    "targetAmount": 44061,
    "account": "PF72763",
    "manager": "Mada Ellissen",
    "trader": "Chickie Guerreau",
    "tradeDate": "2022-01-11",
    "settlementDate": "2022-01-13",
    "status": "WORK",
    "executedQuantity": 0,
    "broker": "CS",
    "securityType": "CB",
    "transactionType": "BUYL",
    "duration": "FOK",
    "instruction": "LIM",
    "limit": ""
  }
]